### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by opsdisk** [AeonDave/doork#3]
There is an issue with the regex pattern you are using.  Ran this with Python 2.7.3.  Changed line 13 in core.py to this just to test and it worked.  Dump is below.

`is_valid = True #re.match("^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$", url)`

----
```
# python doork.py -t google.com -o log.log



         =============================================== 
        |  Doork v0.2 alpha				|
        |  by AeonDave					|
         =============================================== 


    
    
                                .+MNa+...
                               .MMMMMMMMMMMNa+...
               ...............'JMMMNMMNMNNMMMMMMMMMNa+...
              JMMMMMMMMMMMMNM|`JMMNMMNMMMMNMNMMNMMMMMMMMMN.
             .MMNMMMMMMMMMMMM' JMNMMNMMNMMMNMNMMNMNNMNMMNMF
             JMNMM             JMMMMNMNMNMNMMMNMMNMMNMNMMNF
             JMMNM             JMNMMMNMMMNMMNMMNMMMMMNMMNMF
             JMNMM             JMNMNMMNMMNMNMNMMNMNNMMNMMMF
             JMMNM             JMMMMNMMNMMNMMMNMMNMMNMMNMNF
             JMNMN             JMNMMNMNMNMMNMMNMMNMMMNMMNMF
             JMMNM             JMNMMMNMMMNMMNMMNMMNMNMMNMMF
             JMNMM             JMMNMMNMMNMMNMNMMNMMNMMNMMNF
             JMMNM             JMMMNMMNMMNMMNMMNMNMMNMMNMMF
             JNMMN             JMNMMNMMNMMNMMNMMNMMNMNMMNMF
             JMNMM             JMMNMMNMMNMMNMMNMMNMMNMMNMMF
             JMMNM             JMMMNMMNMMNMMNMMNMMNMMNMMNMF
             JMNMM             JMNMMM"7UMNMMNMMNMMNMMNMMNMF
             JMNMM             JMMNM'   dMNMMNMMNMMNMMNMMNF
             JNMMN             JMMMM.   JMMNMMNMMNMMNMMNMMF
             JMMNM             JMNMMN,..MNMMNMNMNMNMMNMMNMF
             JMNMM             JMNMNMNMMNMNMMNMMMNMMNMNMMNF
             JMMNM             JMMMMNMMNMMMNMMNMMNMNMMNMMMF
             JMMNM             JMNMMMNMMNMNMNMMNMMNMMNMNMNF
             JMNMM             JMMNMNMMNMMMNMMNMNMMNMMMMNMF ,o.  ,o
             JNMMM             JMNMMMNMMNMMNMMNMMNMMNMNMMMF ]8[ dP'
             JMMNM             JMMMNMMNMMNMMNMMNMMNMMNMNMMF ]8d8P
             JMNMM             JMNMMNMMNMNMNMNMMNMMNMMMNMNF ]88b.
             JMMNM             JMMNMMNMMNMMMNMMNMMNMNMNMMMF ]8[`8o
             JMNMM             JMMMMNMNMMNMMNMMNMMNMMNMMNMF ]8[  Y8
             JMNMMMMMMNMMMMMM| JMNMMNMMNMMNMMNMMNMMNMMMNMMF
              7MNMNNMMMMNMNMN\ JMNMMNMMNMMNMNMNMMNMMNMNMM@
                 ''''''''''''' ! JMMNMMNMMNMMNMMMNMMMH9"^ 
                               ,MNMMNMNMMNMH9"^ 
                                .THH9"^ 
    
    
[22:16:46] [INFO] -----Start-----
[22:16:46] [INFO] [*] Starting dork scanner on google.com
Traceback (most recent call last):
  File "doork.py", line 92, in <module>
    main()
  File "doork.py", line 82, in main
    actions.scan(target)
  File "/root/Desktop/doork/lib/actions.py", line 85, in scan
    if core.is_valid_url(target):
  File "/root/Desktop/doork/lib/core.py", line 13, in is_valid_url
    is_valid = re.match("^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$", url)
  File "/usr/lib/python2.7/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

**Comment by AeonDave** [comment]
thank you, i'll update it.
